### PR TITLE
Added functionality to associate a unique Context per Sentry Client

### PR DESCRIPTION
**Pull request by amitjoy**

### CODE REVIEW

**Comment by amitjoy** [comment]
Don't merge now.

**Comment by JochenHiller** [comment]
Could we directly call `return new SentryClient(new NoopConnection(), new ThreadLocalContextManager());` instead of patching the Sentry code?
It seems that we are always using the fallback, or?

**Comment by amitjoy** [comment]
I am currently checking how many Sentry Contexts we do require in our runtime. If we need more than one Sentry Context for Sentry Breadcrumbs, then we unfortunately cannot use `SingletonContextManager`. We then have to stick to the `ThreadLocalContextManager`.

**Comment by JochenHiller** [comment]
Is maybe the `clean()` not called on `ThreadLocalContextManager`?
It seems that Sentry does foresee such needs, and we are not yet using it?

**Comment by amitjoy** [comment]
`io.sentry.context.ContextManager.clear()` will only be called after the work of `SentryClient` is finished. For example, after the breadcrumbs are sent to the sentry server one can clean up the context.

**Comment by amitjoy** [comment]
We just need unique `Context` per Client instance - not per thread. It will solve everything.

**Pull request closed without merging**
